### ISSUE TITLE
QModManager not installing correctly (no errors displayed)

### ISSUE THREAD

**Issue by gespensen** [QModManager/Subnautica#107]
Running the installer normally or as administrator does not install QMods into the Subnautica folder. The install display no errors when installing and completes to the finish GUI. I have verified that the subnautica path is correct both by manually selecting the subnautica button and manually selecting the path. 

I have also downloaded the the install file from Nexus several times with the same results.

Note. I do have steam located on my D: drive "D:\Program Files (x86)\Steam\steamapps\common\Subnautica" 

Subnautica directory after running QMod manager 

![Screenshot (8)](https://user-images.githubusercontent.com/6163544/61723567-38cd1080-ad21-11e9-99af-c911a88323d3.png)

**Comment by AlexejheroYTB** [comment]
Please show me a screenshot of the `Subautica_Data/Managed` folder

**Comment by gespensen** [comment]
Hum I see the QMod file there.
![Screenshot (10)](https://user-images.githubusercontent.com/6163544/61737786-ca4a7b80-ad3d-11e9-91d0-3f20a753d96b.png)

What confused me is the instructions on Nexus Mods
![Screenshot (12)](https://user-images.githubusercontent.com/6163544/61737853-e8b07700-ad3d-11e9-8038-2648d48701ec.png)

They tell me to look for a QMod folder in the Subnautica install directory. I could not find one.
Where do the mods go ?

**Comment by AlexejheroYTB** [comment]
Run `QModManager.exe` from `Subnautica_Data/Managed` and tell me what the output says

**Comment by gespensen** [comment]
No patch detected, install? [Y/N]  
I selected Y and ran QModmanager again. Displayed Patch installed

**Comment by AlexejheroYTB** [comment]
QModManager should now work properly, and you should see a `QMods` folder in your subnautica directory

**Comment by gespensen** [comment]
QMod folder appeared

**Comment by gespensen** [comment]
Thank you for your assistance

**Comment by showgun17** [comment]
please help me fix runtime error(at 52:841): SWbemObjectSet: Invalid class problem while installing qmod manager anyone please help
![Screenshot (29)](https://user-images.githubusercontent.com/97295575/148553594-47b1d2c5-a63b-4d9d-8b7c-361e44bf4a79.png)
