### ISSUE TITLE
Nitrox compatibility

### ISSUE THREAD

**Issue by Coding-Hen** [QModManager/Subnautica#109]
Why is Nitrox not compatible?  The hook is in place and you can get on the multiplayer but you get the big warning sign.

**Comment by AlexejheroYTB** [comment]
Nitrox does not work with QModManager

**Comment by Coding-Hen** [comment]
I know, I wanted to know what the reason was for it not working with it!?
You can install both side by side and they launch so what is the problem?

**Comment by AlexejheroYTB** [comment]
It just doesn't work
